import { SpinBox, Button, StandardButton, ComboBox, Slider, LineEdit, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

WXCode := Window {
    title: app_name;
    icon: @image-url("images/logo.png");
    width: 900px;
    height: 500px;
    default-font-size: 14px;

    // path, scene, size, type
    callback gen-qrcode(string, string, string, int);
    callback save-qrcode(image);

    property <string> app_name;
    property <string> def_url;
    property <string> message;
    property <bool> show-qrcode;
    property <image> qrcode;

    VerticalBox{
        HorizontalBox {
            Image {
                height: 34px; width: 34px;
                source: @image-url("images/arrow.png");
                image-fit: cover;
            }
            Text {
                text: "小程序码生成工具";
                font-size: 24px;
                color: black;
            }
            type-box := ComboBox{
                width: 145px;
                model: ["小程序码", "小程序二维码"];
                current-index: 0;
                current-value: "小程序码";
            }
        }
        HorizontalBox {
            text-edit := LineEdit {
                placeholder-text: "输入小程序页面路径";
                text: def_url;
            }
            scene-edit := LineEdit {
                width: 150px;
                placeholder-text: "输入scene";
                text: "$3D13";
            }
            size-box := ComboBox{
                width: 120px;
                height: 50px;
                model: ["320*320", "430*430", "500*500", "600*600", "700*700", "800*800"];
                current-value: "430*430";
                preferred-height: 60px;
            }
            btn := Button {
                text: "生成";
                enabled: text-edit.text != "";
                clicked => {
                    gen-qrcode(text-edit.text, scene-edit.text, size-box.current-value, type-box.current-index);
                }
            }
        }
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                alignment: center;
                visible: root.show-qrcode;
                Image {
                    height: 300px;
                    width: 300px;
                    source: root.qrcode;
                    image-fit: cover;
                }
                Button {
                    text: "保存二维码";
                    clicked => {
                        save-qrcode(root.qrcode);
                    }
                }
            }
        }
    }
    HorizontalLayout {
        visible: !root.show-qrcode;
        y: 200px;
        alignment: center;
        tip-text := Text {
            text: root.message;
            color: lightgray;
            font-size: 40px;
        }
    }
}